#!/usr/bin/env python3
# a simple build system
import sys
import os

# constants #
START_MAKEFILE = """include common.mk
"""

# argument parser #
class ArgumentParser:
    HELP = 0x1 # display help #
    DEPENDENCY = 0x2 # generate a dependency makefile instead of a standalone #

    def __init__(self, argv):
        self.argv = argv

    # print usage #
    def print_usage(self):
        print(f'Usage: {self.argv[0]} [options]\n\noptions:\n\t-help\tPrint usage\n\t-dep\tGenerate dependency makefiles (include *.mk)')

    # parse arguments #
    def parse(self):
        flags = 0

        for arg in self.argv:
            if arg[0] == '-':
                if arg == '-help':
                    self.print_usage()
                    flags |= ArgumentParser.HELP
                elif arg == '-dep':
                    flags |= ArgumentParser.DEPENDENCY
                else:
                    print(f'Unrecognized option: \'{arg}\'')
                    self.print_usage()
                    flags |= ArgumentParser.HELP

        return flags

# target object #
class TargetObject:
    __slots__ = (
            'name',
            'flags',
            'out',
            'srcdir',
            'objdir',
            'depsdir',
            'cflags',
            'asmflags',
            'ldflags',
            'cfiles',
            'asmfiles',
            )

    def __init__(self, module, target):
        self.name = target.get('name', '')
        self.flags = module.flags + target.get('flags', ())
        self.out = target.get('out', '')
        self.srcdir = target.get('srcdir', module.srcdir)
        self.objdir = target.get('objdir', module.objdir)
        self.depsdir = target.get('depsdir', module.depsdir)
        self.cflags = module.cflags + target.get('cflags', '')
        self.asmflags = module.asmflags + target.get('asmflags', '')
        self.ldflags = module.ldflags + target.get('ldflags', '')
        self.cfiles = target.get('c-files', ())
        self.asmfiles = target.get('asm-files', ())

# module object #
class ModuleObject:
    __slots__ = (
            'name',
            'targets',
            'flags',
            'srcdir',
            'objdir',
            'depsdir',
            'cflags',
            'asmflags',
            'ldflags',
            )

    def __init__(self, module):
        self.name = module.get('name', '')
        self.targets = module.get('targets', ())
        self.flags = module.get('flags', ())
        self.srcdir = module.get('srcdir', '')
        self.objdir = module.get('objdir', '')
        self.depsdir = module.get('depsdir', '')
        self.cflags = module.get('cflags', '')
        self.asmflags = module.get('asmflags', '')
        self.ldflags = module.get('ldflags', '')

        self.targets = tuple(TargetObject(self, target) for target in self.targets)

# makefile generator #
class MakefileGenerator:
    def __init__(self, modules, flags=None):
        self.modules = []
        self.string = None
        self.dep = False # generate dependency makefiles #

        for name in modules:
            self.modules.append(__import__(name).module)

        # interpret flags #
        if flags is not None:
            self.dep = bool(flags & ArgumentParser.DEPENDENCY)

    # generate all associated makefiles #
    def generate_all(self):
        for mod in self.modules:
            self.generate(mod)

    # generate associated makefile #
    def generate(self, mod):
        makefile_fname = f'{mod["name"]}.mk'
        print(f'Generating {makefile_fname}...')

        self.string = START_MAKEFILE

        modobj = ModuleObject(mod)

        # add constants #
        for target in modobj.targets:
            self.add_constants(target)

        # add target list #
        self.string += '\nall:'
        for target in modobj.targets:
            self.string += ' ' + target.out

        # targets #
        for target in modobj.targets:
            self.add_target(target)

        # save file #
        self.string += '\n'
        with open(makefile_fname, 'w') as fp:
            fp.write(self.string)
        self.string = None

    # add constants #
    def add_constants(self, target):
        nolink = 'NO_LINK' in target.flags

        name = target.name.upper()
        objdir = target.objdir

        # cflags #
        self.string += f'\n{name}_CFLAGS=-c {target.cflags}'

        # asmflags #
        self.string += f'\n{name}_ASMFLAGS={target.asmflags}'

        if not nolink:
            # ldflags #
            self.string += f'\n{name}_LDFLAGS={target.ldflags}'

            # objfiles #
            self.string += f'\n{name}_OBJFILES='
            self.add_objfiles(objdir, target.cfiles)
            self.add_objfiles(objdir, target.asmfiles)
            self.string += '\n'

    # add object files #
    def add_objfiles(self, objdir, files):
        for src in files:
            fname = src[0] if isinstance(src, tuple) else src
            self.string += os.path.join(objdir, os.path.splitext(os.path.basename(fname))[0] + '.o ')

    # add target #
    def add_target(self, target):
        nolink = 'NO_LINK' in target.flags
        hostcc = 'HOST_CC' in target.flags

        name = target.name.upper()
        out = target.out

        linker = 'HOST_CC' if hostcc else 'LD'
        if not nolink:
            self.string += f'\n\n{out}: $({name}_OBJFILES)\n\t$(DST_FILENAME)\n\t@$({linker}) -o {out} $({name}_OBJFILES) $({name}_LDFLAGS)'

        # add source rules #
        self.add_source_rules(target, target.cfiles)
        self.add_source_rules(target, target.asmfiles, ext='asm')

    # add source rules #
    def add_source_rules(self, target, files, ext='c'):
        nolink = 'NO_LINK' in target.flags
        hostcc = 'HOST_CC' in target.flags

        comp='ASM' if ext == 'asm' else 'HOST_CC' if hostcc else 'CC'
        flags='ASMFLAGS' if ext == 'asm' else 'CFLAGS'
        name = target.name.upper()
        srcdir = target.srcdir
        objdir = target.objdir
        depsdir = target.depsdir

        for src in files:
            fname = src[0] if isinstance(src, tuple) else src
            deps = src[1:] if isinstance(src, tuple) else None
            objfile = os.path.splitext(os.path.basename(fname))[0] + '.o'

            fname = os.path.join(srcdir, fname)
            objfile = os.path.join(objdir, objfile)

            if nolink: objfile = target.out

            self.string += f'\n\n{objfile}: {fname}'
            if deps:
                for dep in deps:
                    self.string += ' ' + os.path.join(depsdir, dep)

            self.string += f'\n\t$(SRC_FILENAME)\n\t@$({comp}) $({name}_{flags}) -o {objfile} {fname}'

# main #
def main():
    from modules import modules

    # parse arguments #
    argparse = ArgumentParser(sys.argv)
    flags = argparse.parse()

    if flags & ArgumentParser.HELP:
        return

    # generate makefiles #
    makegen = MakefileGenerator(modules, flags)
    makegen.generate_all()

if __name__ == '__main__':
    main()
